# For dev env. 
version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: # To mount local reference into the container.
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]